# Generated by Django 5.0.4 on 2024-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(default='p', max_length=20),
        ),
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
