# Generated by Django 5.0.4 on 2024-04-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_status_delete_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mailid',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
