# Generated by Django 5.0.4 on 2024-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_mailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mailid',
            field=models.CharField(max_length=255),
        ),
    ]
